config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'about' => 'main#about'

  get 'cart' => 'cart#show'
  patch 'cart' => 'cart#update' 

  resource :sessions, only: [:new,:create,:destroy]
  resources :users
  resources :products do
    resources :reviews
    resources :cart_products, only: [:create, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :cart_owner, class_name: "User", foreign_key: "cart_owner_id"
  has_one :status
  has_many :cart_products
  has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"
  has_many :order_items
  has_many :cart_products
  has_many :carts, through: :cart_products

  validates :name,:description,:price_in_cents, :product_image, presence: true
  validates :price_in_cents, numericality: true, numericality: {greater_than: 0}

  mount_uploader :product_image, ProductImageUploader

  def convert_dollars
    price_in_cents / 100.00
  end

  def self.search(search)
    # same as 'Product.where(same as below)'
    where("name LIKE ?", "%#{search}%")
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :review_text, presence: true

  after_destroy :log_destroy_action

  def writer
    user.username
  end

  def log_destroy_action
    puts "Article destroyed"
  end
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :owned_products, class_name: "Product", dependent: :destroy
  has_many :products, through: :reviews
  has_many :carts

  has_secure_password

  validates :username, uniqueness: true
  validates :email, uniqueness: true
  validates :username,:email,:password,:password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # allows us to use current_user and current_order in views
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please sign in."
      redirect_to new_sessions_path
    end
  end

  # retrieve product_id from query params (for nested resource)
  def load_product
    @product = Product.find(params[:product_id])
  end

  # returns the first item or nil.
  def load_cart
    # look for cart with current_user_id
    # if none exist, create new cart
    @cart = Cart.find_by(cart_owner_id: session[:user_id], status_id: 1)
    if @cart == nil
      @cart = Cart.new
      @cart.cart_owner_id = current_user.id
      @cart.status_id = 1
      @cart.save
    end
  end


end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :current_user, :load_cart

  def show
    @cart_products = @cart.cart_products.all.to_a
    @subtotal = subtotal
  end

  def update
    @cart.status_id = 2
    if @cart.save
      flash.now[:notice] = 'Items checked out!'
      redirect_to cart_path
    else
      render cart_path
    end

  end

  private
  def subtotal
    @cart_products.inject(0) {|sum,item| sum+ Product.find(item.product_id).price_in_cents}
  end
end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController
  before_action :load_cart, :load_product
  before_action :ensure_logged_in, only: [:create,:update, :destroy]

  def create
    @cart_product = @product.cart_products.create(cart_product_params)
    @cart_product.cart = @cart
    if @cart_product.save
      redirect_to product_path(params[:product_id])
    else
      render :product
    end
  end

  def update
  end

  def destroy
    @cart_product = CartProduct.find(params[:id])
    @cart_product.destroy
    redirect_to cart_path
  end

  private

  def cart_product_params
    params.require(:cart_product).permit(:quantity, :cart_id, :product_id)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :current_user

  def index
    @products = Product.all
    if params[:search]
      @products = Product.search(params[:search]).order("created_at DESC")
    else
      @products = Product.order("created_at DESC")
    end
  end

  def show
    @product = Product.find(params[:id])

    if session[:user_id] != nil
      load_cart
      @cart_product = @product.cart_products.build
    end

    # list all reviews
    @reviews = @product.reviews.all

    # add review
    # what you normally put in reviews#new
    @review = @product.reviews.build
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.owner = current_user
    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to products_url
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents, :product_image)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :load_product
  before_action :ensure_logged_in, only: [:create,:destroy]

  def show
  end

  def create
    @review = @product.reviews.create(review_params)
    @review.user = current_user

    if @review.save
      redirect_to product_path(params[:product_id])
    else
      render :product
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(params[:product_id]), notice: 'Review removed.'
  end

  private
  def review_params
    params.require(:review).permit(:review_text,:product_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # checks if user exists
    user = User.find_by(email:params[:email])

    # checks whether password matches with user email
    if user && user.authenticate(params[:password])
      # saves user in a cookie
      session[:user_id] = user.id
      redirect_to products_path, notice: "Signed in."
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    # session[:cart_id] = nil
    redirect_to root_path, notice: "User logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user)
    @products = owned_products_list.order("created_at DESC")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(current_user)
  end

  def update
    @user = User.find(current_user)
    if @user.update_attributes(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:password,:password_confirmation)
  end

  def owned_products_list
    Product.where("owner_id = ?", current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart/show.html.erb
<div class = "content-container">
  <div class = "container">
    <div class = "container">
      <h2>Your Cart</h2>

      <% if @cart_products.size == 0 %>
        <em>There are no items in your shopping cart. Please go <%= link_to "back", products_path %> to add some items to your cart.</em>

      <% else %>
          <table>
            <thead>
              <tr>
                <th></th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @cart_products.each do |item| %>
                <% product = Product.find(item.product_id) %>
                <tr class = "cart-item-display">
                  <td class = "cart-item-image">
                    <%= image_tag("#{product.product_image}") %>
                  </td>
                  <td>
                    <%= product.name %>
                  </td>
                  <td><%= item.quantity %></td>
                  <td>$<%= product.price_in_cents / 100.00 %></td>
                  <td><%= link_to "remove", product_cart_product_path(product.id, item.id), method: :delete %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <div class="cart-total">
            <div class="total-amount">
              Subtotal: &nbsp $<%= @subtotal / 100.00%>
            </div>
            <div class="btn-checkout">
              <%= link_to "", data:{toggle:"modal", target:"#checkout-modal"} do %>
                <div class="checkout-cart">Confirm Checkout </div>
              <% end %>
            </div>
          </div>

          <div id="checkout-modal" class="modal fade" role="dialog">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Please confirm your order</h4>
                </div>
                <div class="modal-body">
                  <p>
                    You are about to checkout.
                  </p>
                </div>
                <div class="modal-footer">
                  <%= link_to cart_path, method: :patch, data:{dismiss: "modal"} do %>
                    <div class="btn btn-default">Confirm</div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>

        <% end %>

    </div>
  </div>
</div>