config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'about' => 'main#about'

  get 'cart' => 'cart#show'
  patch 'cart' => 'cart#update' 

  resource :sessions, only: [:new,:create,:destroy]
  resources :users
  resources :products do
    resources :reviews
    resources :cart_products, only: [:create, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :cart_owner, class_name: "User", foreign_key: "cart_owner_id"
  has_one :status
  has_many :cart_products
  has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"
  has_many :order_items
  has_many :cart_products
  has_many :carts, through: :cart_products

  validates :name,:description,:price_in_cents, :product_image, presence: true
  validates :price_in_cents, numericality: true, numericality: {greater_than: 0}

  mount_uploader :product_image, ProductImageUploader

  def convert_dollars
    price_in_cents / 100.00
  end

  def self.search(search)
    # same as 'Product.where(same as below)'
    where("name LIKE ?", "%#{search}%")
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :review_text, presence: true

  after_destroy :log_destroy_action

  def writer
    user.username
  end

  def log_destroy_action
    puts "Article destroyed"
  end
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :owned_products, class_name: "Product", dependent: :destroy
  has_many :products, through: :reviews
  has_many :carts

  has_secure_password

  validates :username, uniqueness: true
  validates :email, uniqueness: true
  validates :username,:email,:password,:password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # allows us to use current_user and current_order in views
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please sign in."
      redirect_to new_sessions_path
    end
  end

  # retrieve product_id from query params (for nested resource)
  def load_product
    @product = Product.find(params[:product_id])
  end

  # returns the first item or nil.
  def load_cart
    # look for cart with current_user_id
    # if none exist, create new cart
    @cart = Cart.find_by(cart_owner_id: session[:user_id], status_id: 1)
    if @cart == nil
      @cart = Cart.new
      @cart.cart_owner_id = current_user.id
      @cart.status_id = 1
      @cart.save
    end
  end


end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :current_user, :load_cart

  def show
    @cart_products = @cart.cart_products.all.to_a
    @subtotal = subtotal
  end

  def update
    @cart.status_id = 2
    if @cart.save
      flash.now[:notice] = 'Items checked out!'
      redirect_to cart_path
    else
      render cart_path
    end

  end

  private
  def subtotal
    @cart_products.inject(0) {|sum,item| sum+ Product.find(item.product_id).price_in_cents}
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :current_user

  def index
    @products = Product.all
    if params[:search]
      @products = Product.search(params[:search]).order("created_at DESC")
    else
      @products = Product.order("created_at DESC")
    end
  end

  def show
    @product = Product.find(params[:id])

    if session[:user_id] != nil
      load_cart
      @cart_product = @product.cart_products.build
    end

    # list all reviews
    @reviews = @product.reviews.all

    # add review
    # what you normally put in reviews#new
    @review = @product.reviews.build
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.owner = current_user
    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to products_url
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents, :product_image)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :load_product
  before_action :ensure_logged_in, only: [:create,:destroy]

  def show
  end

  def create
    @review = @product.reviews.create(review_params)
    @review.user = current_user

    if @review.save
      redirect_to product_path(params[:product_id])
    else
      render :product
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(params[:product_id]), notice: 'Review removed.'
  end

  private
  def review_params
    params.require(:review).permit(:review_text,:product_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # checks if user exists
    user = User.find_by(email:params[:email])

    # checks whether password matches with user email
    if user && user.authenticate(params[:password])
      # saves user in a cookie
      session[:user_id] = user.id
      redirect_to products_path, notice: "Signed in."
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    # session[:cart_id] = nil
    redirect_to root_path, notice: "User logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user)
    @products = owned_products_list.order("created_at DESC")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(current_user)
  end

  def update
    @user = User.find(current_user)
    if @user.update_attributes(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:password,:password_confirmation)
  end

  def owned_products_list
    Product.where("owner_id = ?", current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>

  <% if @product.errors.any? %>
    <%= pluralize(@product.errors.count,"error") %> prevented you from saving.
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :price_in_cents %>
    <%= f.text_field :price_in_cents %>
  </div>
  <div>
    <%= f.label :product_image %>
    <%= f.file_field :product_image %>
  </div>
  <div class = "form-submit">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class ="content-container">
  <div class ="container">
    <h1>Edit Item</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/products/index.html.erb
<div class = "content-container search-items">
  <div class = "container">

    <div class = "search-form col-md-12">
      <%= form_tag(products_path, method: "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Products" %>
        <!-- have :name nil makes url nicer -->
        <%= submit_tag "Search", class: "search-button", :name => nil %>
      <% end %>
    </div>

    <% if @products.blank? && @products.count > 0%>
      <div class = "col-md-12 no-search-results">
        <p>
          Sorry, there are no products containing <em><%= params[:search] %></em>.
        </p>
        <div class = "product-thumb-indiv">
          <% if current_user %>
            <%= link_to new_product_path do %>
              <div class = "product-square no-search-add">
                <i class="fa fa-plus" aria-hidden="true"></i> &nbsp
                Create Item
              </div>
            <% end %>
          <% end %>
        </div>
      </div>

    <% elsif @products.blank? && @products.count == 0%>
      <div class = "col-md-12 no-search-results">
        <p>
          There are currently no items in the marketplace.
        </p>
        <div class = "product-thumb-indiv">
          <% if current_user %>
            <%= link_to new_product_path do %>
              <div class = "product-square no-search-add">
                <i class="fa fa-plus" aria-hidden="true"></i> &nbsp
                Create Item
              </div>
            <% end %>
          <% end %>
        </div>
      </div>

    <% else %>
      <% @products.each do |product| %>
        <div class="col-xs-6 col-sm-4 col-md-3 col-lg-3 product-thumb-indiv">
          <div class="product-square">
           <%= link_to image_tag("#{product.product_image.thumb.url}"), product_path(product) %><br>
           <p>
             <b><%= product.name.titleize %></b><br>
             $ <%= '%.2f' % product.convert_dollars %>
           </p>
         </div>
        </div>
      <% end %>

      <div class = "col-xs-6 col-sm-4 col-md-3 col-lg-3 product-thumb-indiv">
        <% if current_user %>
          <%= link_to new_product_path do %>
            <div class = "product-square add-item">
              <i class="fa fa-plus fa-2x" aria-hidden="true"></i><br><br>
              Create Item
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>

  </div>
</div>

app/views/products/new.html.erb
<div class = "content-container" >
  <div class = "container">
    <h2>Add New Product</h2>

    <%= render 'form' %>
  </div>
</div>

app/views/products/show.html.erb
<div class = "content-container item-desc">
  <div class = "container">
    <div class = "container">

      <h2 class = "col-sm-12 col-md-12 item-name"><%= @product.name.titleize %></h2>

      <div class = "col-sm-7 col-md-5 product-image">
        <%= image_tag @product.product_image.url if @product.product_image? %><br>
      </div>

      <div class = "col-sm-5 col-md-7">
        <div class = "item-desc-subcat">
          Item Description:
        </div>
        <%= @product.description %><br>

        <div class = "item-desc-subcat price">
          Price: $ <%= '%.2f' % @product.convert_dollars %>
        </div>

        <div class= "add-cart add-to-cart">
          <!-- remote: true means that js will control behavior (ie. Ajax submit) -->
          <% if session[:user_id] != nil && session[:user_id] != @product.owner_id%>
            <%= form_for ([@product,@cart_product]) do |f| %>
              <%= f.number_field :quantity, value:1, min:1, class: "quantity-cart" %>
              <%= f.submit "Add to Cart" %>
            <% end %>
          <% elsif session[:user_id] == @product.owner_id%>
            <em> Sorry, you cannot purchase your own item.</em>
          <% end %>
        </div>

        <% if current_user && @product.owner_id == current_user.id%>
          <div class = "edit_product">
            <%= link_to 'Edit', edit_product_path %> |
            <%= link_to 'Delete', product_path, data: {confirm: "Are you sure you want to remove this item?"}, method: :delete %>
          </div>
        <% end %>
      </div>

      <div class = "col-sm-12 col-md-12">
        <h3>Reviews</h3>
        <% if @reviews.count == 0 %>
          <p><em>There are currently no reviews.</em></p>
        <% else%>
            <% @reviews.each do |review| %>
              <% if review.review_text != nil %>
                <p>
                  <%= review.review_text %><br>

                  <em>Reviewed by <%= review.writer %> at <%= review.created_at.strftime("%b.%d, %Y" + " at " + "%l:%M %p") %></em><br>

                  <% if review.id != nil && current_user && review.user_id == current_user.id %>
                    <%= link_to "delete", [@product, review], method: :delete %>
                  <% end %>
                </p>
              <% end %>
            <% end %>
        <% end %>

        <div class = "form">
          <%= form_for ([@product,@review]) do |f| %>

            <% if @review.errors.any? %>
              <%= pluralize(@review.errors.count,"error") %> prevented you from saving.
              <ul>
                <% @review.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            <% end %>

            <div class = "review-textfield">
              <%= f.label :review_text %><br>
              <%= f.text_area :review_text %><br>
              <%= f.submit "Submit Review" %>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any?  %>
    <%= pluralize(@user.errors.count,"error")%> prohibited this form from saving.
    <ul>
      <% @user.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class = "content-container">
  <div class = "container">
    <div class = "container">
      <h2>Edit Account</h2>

      <p> Please resubmit your password when updating fields. </p>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class = "content-container">
  <div class = "container">
    <h2>Create Account</h2>

    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class = "content-container">
  <div class = "container">
    <div class = "container">
      <h2>Profile</h2>

      <h4>Username</h4>
      <p><%= @user.username %></p>

      <h4>Email</h4>
      <p><%= @user.email %></p>

      <h4>Owned Products</h4>
      <% @products.each do |item|%>
        <div class = "col-sm-2 col-md-2">
          <%= link_to item.name.titleize, product_path(item.id) %>
        </div>
      <% end %>

      <br><br>
      <%= button_to "Edit Profile", edit_user_path(current_user), method: :get, class: "edit-profile-buton" %>
    </div>
  </div>
</div>