config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'about' => 'main#about'

  get 'cart' => 'cart#show'
  patch 'cart' => 'cart#update' 

  resource :sessions, only: [:new,:create,:destroy]
  resources :users
  resources :products do
    resources :reviews
    resources :cart_products, only: [:create, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :cart_owner, class_name: "User", foreign_key: "cart_owner_id"
  has_one :status
  has_many :cart_products
  has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"
  has_many :order_items
  has_many :cart_products
  has_many :carts, through: :cart_products

  validates :name,:description,:price_in_cents, :product_image, presence: true
  validates :price_in_cents, numericality: true, numericality: {greater_than: 0}

  mount_uploader :product_image, ProductImageUploader

  def convert_dollars
    price_in_cents / 100.00
  end

  def self.search(search)
    # same as 'Product.where(same as below)'
    where("name LIKE ?", "%#{search}%")
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :review_text, presence: true

  after_destroy :log_destroy_action

  def writer
    user.username
  end

  def log_destroy_action
    puts "Article destroyed"
  end
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :owned_products, class_name: "Product", dependent: :destroy
  has_many :products, through: :reviews
  has_many :carts

  has_secure_password

  validates :username, uniqueness: true
  validates :email, uniqueness: true
  validates :username,:email,:password,:password_confirmation, presence: true

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :current_user, :load_cart

  def show
    @cart_products = @cart.cart_products.all.to_a
    @subtotal = subtotal
  end

  def update
    @cart.status_id = 2
    if @cart.save
      flash.now[:notice] = 'Items checked out!'
      redirect_to cart_path
    else
      render cart_path
    end

  end

  private
  def subtotal
    @cart_products.inject(0) {|sum,item| sum+ Product.find(item.product_id).price_in_cents}
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :load_product
  before_action :ensure_logged_in, only: [:create,:destroy]

  def show
  end

  def create
    @review = @product.reviews.create(review_params)
    @review.user = current_user

    if @review.save
      redirect_to product_path(params[:product_id])
    else
      render :product
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(params[:product_id]), notice: 'Review removed.'
  end

  private
  def review_params
    params.require(:review).permit(:review_text,:product_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user)
    @products = owned_products_list.order("created_at DESC")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(current_user)
  end

  def update
    @user = User.find(current_user)
    if @user.update_attributes(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:password,:password_confirmation)
  end

  def owned_products_list
    Product.where("owner_id = ?", current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>marketplace</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
    <!-- enable touch zooming and ensure proper rendering on mobile devices  -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=EB+Garamond|Oswald|Open+Sans" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top main-menu-bar">
      <div class="container">
          <span class = "logo">marketplace</span>

          <button type="button" class="navbar-toggle collapsed hamburger-menu" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="main-menu"><%= link_to "Home", root_path%></li>
                <li class="main-menu"><%= link_to "Shop", products_path%></li>

                <% if current_user %>
                  <li class="main-menu"><%= link_to "Profile", user_path('current')%></li>

                  <li class="main-menu"><%= link_to "Cart", cart_path%></li>

                  <li class="main-menu"><%= link_to "Sign Out", sessions_path('current'), method: :delete%></li>
                <% else %>
                  <li class="main-menu"><%= link_to "Sign In", new_sessions_path%></li>
                  <li class="main-menu"><%= link_to "Sign Up", new_user_path%></li>
                <% end %>
            </ul>
          </div>

      </div>
    </nav>
      <%#= flash[:notice] %>
      <%#= flash[:alert] %>

      <%= yield %>
  </body>
</html>

app/views/purchases/index.html.erb
<div class = "content-container search-items">
  <div class = "container">
    <div class = "container">
      <h2>Cart</h2>
      
    </div>
  </div>
</div>

app/views/purchases/show.html.erb
<div class = "content-container search-items">
  <div class = "container">
    <div class = "container">
      <h2>Cart</h2>

    </div>
  </div>
</div>